### ISSUE TITLE
Vertico truncate doesn't work for me

### ISSUE THREAD

**Issue by maikol-solis** [jdtsmith/vertico-truncate#1]
Hi! 
I'm using doom and tried your package unsuccessfully. I put `(vertico-truncate-mode 1)` in my `config.el` file, and it doesn't seem to work. 

This is an example of how I see my recent files. 

![image](https://github.com/jdtsmith/vertico-truncate/assets/4078489/e78ecf81-33b4-4302-8ffb-4f566fbb4316)

Thanks for any help. 

Best.

**Comment by jdtsmith** [comment]
This package is working with consult-buffer and consult-*grep; did you try with those?

**Comment by maikol-solis** [comment]
With consult-buffer and consult-grep I can see all the candidates without problem (even the long ones) 

![image](https://github.com/jdtsmith/vertico-truncate/assets/4078489/4b968b41-eaec-4fec-a504-a9819d65d60c)

![image](https://github.com/jdtsmith/vertico-truncate/assets/4078489/4c5de3ac-9c49-45ba-847d-2b1f1f5a2310)


The problem is when I try to reach long named directories with `consult-recent-files`:

![image](https://github.com/jdtsmith/vertico-truncate/assets/4078489/d5ebdd2c-382a-4429-972e-6787298d76ef)

**Comment by jdtsmith** [comment]
Just pushed a change to work with generic `'file` category.  I'm hoping that doesn't cause problems elsewhere; give a try and let me know.

**Comment by maikol-solis** [comment]
Now it works as expected. Thanks. 

![image](https://github.com/jdtsmith/vertico-truncate/assets/4078489/e1901b9f-9f4c-4870-9b00-bb45178355d6)
