### ISSUE TITLE
Truncation but marginalia information still off screen.

### ISSUE THREAD

**Issue by oncomouse** [jdtsmith/vertico-truncate#2]
I'm using `vertico-truncate` and it is truncating correctly, but despite the truncation, `marginalia` information still overflows offscreen (see the screenshot, below). Is there anyway to fix this so that marginalia information can show up as well?

![vertico-truncated](https://github.com/jdtsmith/vertico-truncate/assets/2666761/f66be1c6-cc2b-40f5-8d0f-83b79aff65c8)

**Comment by jdtsmith** [comment]
What does `M-: (vertico--window-width)` say?  I suspect you have something wrong with your marginalia settings, since all the shorter files are not altered, yet still don't show the suffix data.  What do you see when you disable `vertico-truncate`?

**Comment by oncomouse** [comment]
For `M-: (vertico--window-width)`, it says `114 (#o162, #x72), ?r)`. With `vertico-truncated` disabled, I see what's in the screenshot below, which is the untruncated file names and the same problem with marginalia. You can't see it in the screenshot, but there's a very long file name offscreen, which is why (I suppose) the marginalia information is being displaced.

I'm using Doom emacs and [this is the configuration for marginalia](https://github.com/doomemacs/doomemacs/blob/986398504d09e585c7d1a8d73a6394024fe6f164/modules/completion/vertico/config.el#L313-L333), which doesn't look too far off the recommended settings. I also just checked in a different emacs configuration I have that also uses vertico, and it has the same problem.

![vertico-truncated-2](https://github.com/jdtsmith/vertico-truncate/assets/2666761/1de815a5-650b-4529-89d7-420a7d47e188)

**Comment by jdtsmith** [comment]
OK, so not a vertico-truncate problem.  Not sure what you mean about a very long filename.  I'd update vertico/consult/marginalia to be sure it's not a temporary conflict of some kind.

**Comment by meedstrom** [comment]
I have the same issue. Screenshots follow.

Without truncate mode:

![Screenshot from 2024-07-20 19-00-29](https://github.com/user-attachments/assets/62e8ed21-fe1e-43c7-b383-7ea8e22e6238)


With truncate mode (note the annotations have not moved at all):

![Screenshot from 2024-07-20 19-00-02](https://github.com/user-attachments/assets/e011c429-beae-4935-94df-ebead0825dba)

**Comment by jdtsmith** [comment]
I believe vertico has again changed the way this formatting layout works, and marginalia has its own truncation methods.  Really this functionality belongs upstream, so consider opening issues with vertico/marginalia/consult.
